# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

RESCOMP = windres
DEFINES += -DOATPP_DISABLE_ENV_OBJECT_COUNTERS=ON -DOATPP_BUILD_TESTS=OFF -D_CRT_SECURE_NO_WARNINGS
INCLUDES += -Isrc -I../oatpp/src -I/usr/include/postgresql
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LINKCMD = $(AR) -rcs "$@" $(OBJECTS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug)
TARGETDIR = bin/Debug-linux-x86_64/oatpp-postgresql
TARGET = $(TARGETDIR)/liboatpp-postgresql.a
OBJDIR = bin-int/Debug-linux-x86_64/oatpp-postgresql
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -g -std=c++20
LIBS += ../oatpp/bin/Debug-linux-x86_64/oatpp/liboatpp.so
LDDEPS += ../oatpp/bin/Debug-linux-x86_64/oatpp/liboatpp.so
ALL_LDFLAGS += $(LDFLAGS) -Lvendor/oatpp/binDebug-linux-x86_64/oatpp -L/usr/lib64 -Wl,-rpath,'$$ORIGIN/../../../../oatpp/bin/Debug-linux-x86_64/oatpp' -m64

else ifeq ($(config),release)
TARGETDIR = bin/Release-linux-x86_64/oatpp-postgresql
TARGET = $(TARGETDIR)/liboatpp-postgresql.a
OBJDIR = bin-int/Release-linux-x86_64/oatpp-postgresql
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -std=c++20
LIBS += ../oatpp/bin/Release-linux-x86_64/oatpp/liboatpp.so
LDDEPS += ../oatpp/bin/Release-linux-x86_64/oatpp/liboatpp.so
ALL_LDFLAGS += $(LDFLAGS) -Lvendor/oatpp/binRelease-linux-x86_64/oatpp -L/usr/lib64 -Wl,-rpath,'$$ORIGIN/../../../../oatpp/bin/Release-linux-x86_64/oatpp' -m64 -s

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/Connection.o
GENERATED += $(OBJDIR)/ConnectionProvider.o
GENERATED += $(OBJDIR)/Deserializer.o
GENERATED += $(OBJDIR)/Executor.o
GENERATED += $(OBJDIR)/Parser.o
GENERATED += $(OBJDIR)/PgArray.o
GENERATED += $(OBJDIR)/QueryResult.o
GENERATED += $(OBJDIR)/ResultMapper.o
GENERATED += $(OBJDIR)/Serializer.o
GENERATED += $(OBJDIR)/TemplateValueProvider.o
GENERATED += $(OBJDIR)/Uuid.o
OBJECTS += $(OBJDIR)/Connection.o
OBJECTS += $(OBJDIR)/ConnectionProvider.o
OBJECTS += $(OBJDIR)/Deserializer.o
OBJECTS += $(OBJDIR)/Executor.o
OBJECTS += $(OBJDIR)/Parser.o
OBJECTS += $(OBJDIR)/PgArray.o
OBJECTS += $(OBJDIR)/QueryResult.o
OBJECTS += $(OBJDIR)/ResultMapper.o
OBJECTS += $(OBJDIR)/Serializer.o
OBJECTS += $(OBJDIR)/TemplateValueProvider.o
OBJECTS += $(OBJDIR)/Uuid.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking oatpp-postgresql
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning oatpp-postgresql
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) del /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/Connection.o: src/oatpp-postgresql/Connection.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ConnectionProvider.o: src/oatpp-postgresql/ConnectionProvider.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Executor.o: src/oatpp-postgresql/Executor.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/QueryResult.o: src/oatpp-postgresql/QueryResult.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Deserializer.o: src/oatpp-postgresql/mapping/Deserializer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PgArray.o: src/oatpp-postgresql/mapping/PgArray.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ResultMapper.o: src/oatpp-postgresql/mapping/ResultMapper.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Serializer.o: src/oatpp-postgresql/mapping/Serializer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Uuid.o: src/oatpp-postgresql/mapping/type/Uuid.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Parser.o: src/oatpp-postgresql/ql_template/Parser.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TemplateValueProvider.o: src/oatpp-postgresql/ql_template/TemplateValueProvider.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif